workflows:
  flutter-android:
    name: Flutter Android Build
    instance_type: linux_x2
    environment:
      flutter: 3.29.2
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - name: Set gradlew executable permissions
        script: chmod +x ./gradlew 
      - name: Build debug APK
        script: ./gradlew :app:assembleDebug 
    artifacts:
      - build app-release.apk
    publishing:
      email:
        recipients:
          - zyghl12@163.com

