workflows:
  flutter-android:
    name: Flutter Android Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: 3.29.2
      vars:
        PACKAGE_NAME: "com.example.myapp"
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - zyghl12@163.com

