
workflows:
  flutter-android:
    name: Flutter Android Build
    environment:
      flutter: 3.29.2 
      vars:
        PACKAGE_NAME: "com.example.flutterapp"   # 替换为你的应用包名
    scripts:
      - flutter packages get  # 获取项目依赖
      - flutter analyze        # 代码静态分析，确保无语法错误
      - flutter test           # 运行测试（可选）
      - flutter build apk --release  # 生成 Release 版本 APK
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
